/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedTestRouteImport } from './routes/_authed/test'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedStudyIndexRouteImport } from './routes/_authed/study/index'
import { Route as AuthedStudyNewRouteImport } from './routes/_authed/study/new'
import { Route as AuthedStudyStudyIdRouteImport } from './routes/_authed/study/$studyId'
import { Route as AuthedStudyEditStudyIdRouteImport } from './routes/_authed/study/edit/$studyId'

const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTestRoute = AuthedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudyIndexRoute = AuthedStudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudyNewRoute = AuthedStudyNewRouteImport.update({
  id: '/study/new',
  path: '/study/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudyStudyIdRoute = AuthedStudyStudyIdRouteImport.update({
  id: '/study/$studyId',
  path: '/study/$studyId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudyEditStudyIdRoute = AuthedStudyEditStudyIdRouteImport.update({
  id: '/study/edit/$studyId',
  path: '/study/edit/$studyId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/test': typeof AuthedTestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/study/$studyId': typeof AuthedStudyStudyIdRoute
  '/study/new': typeof AuthedStudyNewRoute
  '/study/': typeof AuthedStudyIndexRoute
  '/study/edit/$studyId': typeof AuthedStudyEditStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/test': typeof AuthedTestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/study/$studyId': typeof AuthedStudyStudyIdRoute
  '/study/new': typeof AuthedStudyNewRoute
  '/study': typeof AuthedStudyIndexRoute
  '/study/edit/$studyId': typeof AuthedStudyEditStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/test': typeof AuthedTestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authed/study/$studyId': typeof AuthedStudyStudyIdRoute
  '/_authed/study/new': typeof AuthedStudyNewRoute
  '/_authed/study/': typeof AuthedStudyIndexRoute
  '/_authed/study/edit/$studyId': typeof AuthedStudyEditStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/rss.xml'
    | '/onboarding'
    | '/profile'
    | '/test'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/'
    | '/study/$studyId'
    | '/study/new'
    | '/study/'
    | '/study/edit/$studyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/rss.xml'
    | '/onboarding'
    | '/profile'
    | '/test'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog'
    | '/study/$studyId'
    | '/study/new'
    | '/study'
    | '/study/edit/$studyId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/rss.xml'
    | '/_authed/onboarding'
    | '/_authed/profile'
    | '/_authed/test'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/'
    | '/_authed/study/$studyId'
    | '/_authed/study/new'
    | '/_authed/study/'
    | '/_authed/study/edit/$studyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/test': {
      id: '/_authed/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthedTestRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/study/': {
      id: '/_authed/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof AuthedStudyIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/study/new': {
      id: '/_authed/study/new'
      path: '/study/new'
      fullPath: '/study/new'
      preLoaderRoute: typeof AuthedStudyNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/study/$studyId': {
      id: '/_authed/study/$studyId'
      path: '/study/$studyId'
      fullPath: '/study/$studyId'
      preLoaderRoute: typeof AuthedStudyStudyIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/study/edit/$studyId': {
      id: '/_authed/study/edit/$studyId'
      path: '/study/edit/$studyId'
      fullPath: '/study/edit/$studyId'
      preLoaderRoute: typeof AuthedStudyEditStudyIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedTestRoute: typeof AuthedTestRoute
  AuthedStudyStudyIdRoute: typeof AuthedStudyStudyIdRoute
  AuthedStudyNewRoute: typeof AuthedStudyNewRoute
  AuthedStudyIndexRoute: typeof AuthedStudyIndexRoute
  AuthedStudyEditStudyIdRoute: typeof AuthedStudyEditStudyIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedTestRoute: AuthedTestRoute,
  AuthedStudyStudyIdRoute: AuthedStudyStudyIdRoute,
  AuthedStudyNewRoute: AuthedStudyNewRoute,
  AuthedStudyIndexRoute: AuthedStudyIndexRoute,
  AuthedStudyEditStudyIdRoute: AuthedStudyEditStudyIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
